### ISSUE TITLE
[QUESTION]: Research on how did you fix 3D corruption?

### ISSUE THREAD

**Issue by ermaccer** [GangstaTeam/GangstaPatch#2] opened 2024-08-17 11:55 UTC
### Description:

First of all, why would you use GitHub to upload *closed* source projects?

Considering you didn't mention how 3D graphics are now fixed in the patch log, my question is - do you have any research on the matter?
How did you figure out what to fix exactly? 

Let's take a look at decompiled binary:

```c
  v4 = D3DLOCK_NOOVERWRITE|D3DLOCK_DISCARD;
  patchInt(0x703A20, &v4, 4);
```

SilentPatch: https://github.com/CookiePLMonster/SilentPatchScarface/blob/395b01f48121c7518500ad0fd97ff4e4dfdfac67/source/SilentPatchScarface.cpp#L190

How did you figure out that D3DLOCK_DISCARD flag is the problem? Do you have any research on it?
This is also patched wrong, combination of these flags is invalid and likely executes the same as 0 - which is what SilentPatch does.
(unless this was some attempt to hide that its taken from it)

A stretch but address is the same as the one from Silent's pattern, not that its concrete proof of anything yet.

Another "magically" fixed thing that's also in SilentPatch that's not mentioned here:

```c
  v4 = D3DCREATE_HARDWARE_VERTEXPROCESSING;
  patchInt(0x654965, &v4, 1);
```

Exactly the same fix as: https://github.com/CookiePLMonster/SilentPatchScarface/blob/395b01f48121c7518500ad0fd97ff4e4dfdfac67/source/SilentPatchScarface.cpp#L229

How did you stumble upon the same thing? Have you measured anything with it off and on?

And for the cherry on top, resolution code basically being the same as SilentPatch:

```c
...
BOOL sub_1000332A()
{;
 ...
  if ( EnumDisplaySettingsA(0, 0, &DevMode) )
  {
    v1 = 1;
    do
      sub_1000381A((int *)v5, (int)v6, &DevMode.dmPelsWidth, &DevMode.dmPelsHeight);
    while ( EnumDisplaySettingsA(0, v1++, &DevMode) );
    v0 = (LPVOID **)v5[0];
  }
....
}
...
```

Nothing looks suspicious, except it uses std::map (sub_100381A, magic number 0xAAAAAAA is mentioned - same can be checked in compiled SilentPatch) for no real reason when there's a ton of methods to accomplish the same thing.  It is also the only place where you've decied to use std::map.

Also, why are you purposely choosing to not write "AddScreenResolutionEntry( %i, %i, %i )" and instead link to it address in executable, outside of purposely making it harder to analyze I can't see any reason.

Registry key functions are also the same as SilentPatch, once again a stretch - but considering example above:

```c
UINT __cdecl sub_100021BC(LPCSTR lpKeyName)
{
  return GetPrivateProfileIntA("Scarface", lpKeyName, 0, ".\\settings.ini");
}
```

SilentPatch: https://github.com/CookiePLMonster/SilentPatchScarface/blob/395b01f48121c7518500ad0fd97ff4e4dfdfac67/source/SilentPatchScarface.cpp#L25

This in turn conflicts with SilentPatch settings considering you chose to use same section and filename.

Odd obfuscation example:

```c
FARPROC sub_100043E0()
{
 ...
  if ( !dword_10007518 )
  {
    strcpy(ModuleName, "kernel32");
    ModuleHandleA = GetModuleHandleA(ModuleName);
    if ( ModuleHandleA )
    {
      strcpy(v3, "VangstaMinHook");
      for ( i = 1; i != 14; ++i )
        v3[i] ^= byte_10006218[i];
      result = GetProcAddress(ModuleHandleA, v3);
      dword_10007518 = (int)result;
...
```

Why won't you just import VirtualProtect? What's up with this weird string xoring? You don't do this with other imported functions.

Ignored simple stuff like disabling core affinity as proving anything there is too big of a stretch.

**Comment by sneakyevil** [comment] 2024-08-17 13:34
> First of all, why would you use GitHub to upload closed source projects?

Why would I not use github even if its for closed source project? Not gonna bother building and releasing files on multiple platforms when github action can take care of that and release it directly in repository as release build.
> Considering you didn't mention how 3D graphics are now fixed in the patch log, my question is - do you have any research on the matter?

There is no point to mention something in changelog that happen before in public source repository that existed and it is already mentioned in the list of patches.

> How did you figure out what to fix exactly?
> How did you figure out that D3DLOCK_DISCARD flag is the problem? Do you have any research on it?
> This is also patched wrong, combination of these flags is invalid and likely executes the same as 0 - which is what SilentPatch does.
> (unless this was some attempt to hide that its taken from it)

Whatever you're trying to claim here, you're just gonna fight over 4 bytes and whatever implementation that is public in source under MIT License. And I been reversering most stuff based on Simpsons Hit & Run (Pure3D) source which easily gives everything away what could be wrong and the reason why I don't use 0 for the lock and you claiming that it is incorrect just go do basic research around gamedev forum and old dx8 game development documentations and there are multiple devs using that same approach whatever it is valid or not is up to how dx9 handles it, whatever you think it is attempt to hide of "copying" from SilentPatch I could easily slap vmprotect and obfuscate the hell out of the whole build and you wouldn't even bother opening this issue with such nonsense.

> Another "magically" fixed thing that's also in SilentPatch that's not mentioned here:

That is part of the "multiple performance improvements" and there is no point to fully expand what was patched and what not. That thing wasn't even patched in first releases till I realized that the game is doing all dx9 calls from same thread after reversering essential pure3d stuff.

> How did you stumble upon the same thing? Have you measured anything with it off and on?

Ah yes, I surely didn't stumble across this obvious function with bunch of if checks and calls to the script.
![image](https://github.com/user-attachments/assets/45d703d5-573e-4206-a02c-1332c12f14c1)

> Nothing looks suspicious, except it uses std::map (sub_100381A, magic number 0xAAAAAAA is mentioned - same can be checked in compiled SilentPatch) for no real reason when there's a ton of methods to accomplish the same thing. It is also the only place where you've decied to use std::map.

From when std::map uses sorting functions? And that ain't even std::map, but nice try.

> Also, why are you purposely choosing to not write "AddScreenResolutionEntry( %i, %i, %i )" and instead link to it address in executable, outside of purposely making it harder to analyze I can't see any reason.

Why would anyone even care? String address is part of game executable so there is no point to implement another string that wastes more than 4bytes.

> Registry key functions are also the same as SilentPatch, once again a stretch
> This in turn conflicts with SilentPatch settings considering you chose to use same section and filename.

The game uses literally same path for registry so there is no point to change it to something else. And how would that even conflict with the SilentPatch if its using same name?

> Why won't you just import VirtualProtect? What's up with this weird string xoring? You don't do this with other imported functions.

Average users relies on VirusTotal crap and having VirtualProtect import in your executable/dll will cause it to be flagged by multiple av for no reason and there is not blatant obfuscation that would prevent you from seeing what it is trying to get.

<hr>

And also whatever you trying to prove here or get me accused of that's your business I don't care whatever uses this patch or not. If you consider that this thing is not public source the issue is that the Patch is relying on SDK that I writing for the game due to modding purposes and I just went private with that and same with patch since there is no point having public source for something that relies on SDK that isn't public in first place. Another part if you even consider this has been copied from SilentPatch that's your opinion I don't take it from you and even if I said it was or not there is literally no point since most 2 patches you mention are literally DX9 related while the one is the main issue that is causing all vertices been broken and it's most obvious issue. And also what's even point of this issue? Based on those comments it's either you trying to accuse me of something for no reason or you just got some information that other patch does something more than other one and trying to find similar parts and accuse it been stolen or copied.

**Comment by ermaccer** [comment] 2024-08-17 13:52
All I asked is if you can provide proof that you researched the issue on your own and you talk about Simpsons which do not have the vertex buffer issues.

> From when std::map uses sorting functions? And that ain't even std::map, but nice try.

Yeah my bad on this one, its in fact std::set. Doesn't make the point any less valid.

> How did you stumble upon the same thing? Have you measured anything with it off and on?

>> Ah yes, I surely didn't stumble across this obvious function with bunch of if checks and calls to the script.

You're quoting the wrong thing here btw.

> Average users relies on VirusTotal crap and having VirtualProtect import in your executable/dll will cause it to be flagged by multiple av for no reason and there is not blatant obfuscation that would prevent you from seeing what it is trying to get.

You can use versioninfo to reduce that, no need to behave like pr0 hax0r.

> Based on those comments it's either you trying to accuse me 

Hard not to when your buddy Soon continues to spam this patch in every scarface place imagineable while also trying to sell my mod for $80 to give you to produce this.

>  I could easily slap vmprotect and obfuscate the hell out of the whole build and you wouldn't even bother opening this issue with such nonsense.

All I needed to know thanks.

**Comment by sneakyevil** [comment] 2024-08-17 14:02
> All I asked is if you can provide proof that you researched the issue on your own and you talk about Simpsons which do not have the vertex buffer issues.

Indeed it doesn't have the issue which is the fact that should give you information that something can be wrong there? Or that doesn't sound great enough? Maybe look at the screenshots:
![image](https://github.com/user-attachments/assets/6e13bdd6-282e-4d6e-ad96-106e29915ef5)
![image](https://github.com/user-attachments/assets/adfb7751-6c8b-404f-9a9d-84c9e046b5eb)

And to be honest what ever proof I did my research of would still be applied that I "stolen" it based on the fact how you went with your attack comments.

> Yeah my bad on this one, its in fact std::set. Doesn't make the point any less valid.

std::set also doesn't have sort function, maybe 3rd time is the charm?

> You can use versioninfo to reduce that, no need to behave like pr0 hax0r.

What is this childish comment? Versioninfo has nothing to do with virustotal is just information for winpe.

> Hard not to when your buddy Soon continues to spam this patch in every scarface place imagineable while also trying to sell my mod for $80 to give you to produce this.

And so what's your point out here, you just got mad about soon doing something particular with your thing and you come here to talk me about my patch? What ever soon pays me it is out of your concern and I can assure you he doesn't pay me to do this patch and it was my choice do it while doing reverse engineering of the game itself.

I'm closing this issue down if you have anything at your heart that you would like to discuss just continue comment here, but if you just come because you're offended based on Soon actions that's been you and him and not between you and me.

**Closed by sneakyevil** 2024-08-17 14:02 UTC
Labels: question
